version: '3'

services:
  db:
    image: johnny7ho22/my-mysql
    # container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123  # 設定 root 密碼
    ports:
      - "3307:3306"
    

  web:
    image: johnny7ho22/my-django
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
