# Generated by Django 5.1.4 on 2024-12-13 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='員工姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密碼')),
                ('age', models.IntegerField(verbose_name='年齡')),
                ('job_title', models.SmallIntegerField(choices=[(1, '主管'), (2, '工程師'), (3, '資料庫管理員')], verbose_name='職稱')),
            ],
        ),
        migrations.CreateModel(
            name='HeartFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(max_length=16)),
                ('ChestPainType', models.CharField(max_length=16)),
                ('FastingBS', models.IntegerField(default=0)),
                ('MaxHR', models.IntegerField(default=0)),
                ('ExerciseAngina', models.CharField(max_length=16)),
                ('Oldpeak', models.FloatField()),
                ('ST_Slope', models.CharField(max_length=16)),
                ('HeartDisease', models.IntegerField(default=0)),
                ('Hi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DBA',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_plateform.employee')),
                ('database_type', models.CharField(max_length=16, verbose_name='管理DB的類型')),
            ],
            bases=('ml_plateform.employee',),
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_plateform.employee')),
                ('is_oncall', models.CharField(max_length=16, verbose_name='是否可以oncall')),
            ],
            bases=('ml_plateform.employee',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ml_plateform.employee')),
                ('team_size', models.IntegerField(default=0, verbose_name='管理團隊的規模')),
            ],
            bases=('ml_plateform.employee',),
        ),
    ]
