# Generated by Django 5.1.4 on 2024-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_plateform', '0002_remove_heartfailure_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartfailure',
            name='ChestPainType',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='heartfailure',
            name='ExerciseAngina',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='heartfailure',
            name='ST_Slope',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='heartfailure',
            name='Sex',
            field=models.IntegerField(max_length=16),
        ),
    ]
